[meta]
name        = "Compact"
description = "Minimal, tight spacing, small icons"

[window]
width           = 280
height          = 315
anchor          = ["top", "center"]
margin          = [50, 0, 0, 0]
background      = "$surface"
border          = { radius = 4, width = 1, color = "$primary" }
exclusive       = false
ignore-exclusive = false
keyboard        = "exclusive"
font            = { family = "monospace" }

[widget.input]
font            = { size = 14, weight = "normal" }
color           = "$on-surface"
placeholder     = { text = ">>", color = "$outline" }
background      = "$surface-dim"
border          = { radius = 2, width = 1, color = "$surface-bright" }
caret           = { width = 2.0, color = "$primary" }
selection       = { background = "$primary-container", color = "$on-surface" }
padding         = [6, 8, 6, 8]
align           = "left"

[widget.input.prompt]
enable          = false

[widget.results]
margin          = [4, 0, 0, 0]
padding         = [4, 4, 4, 4]
gap             = 1
border          = { radius = 2, width = 0, color = "#00000000" }
scroll          = "follow"
reverse         = false

[widget.results.scrollbar]
enable          = true

[widget.results.scrollbar.track]
width           = 2
color           = "$surface-dim"
padding         = [0]
margin          = [0]
radius          = 2

[widget.results.scrollbar.thumb]
color           = "$primary"
radius          = 2

[widget.results.item]
icon            = { size = 16, gap = 6, enable = true }
comment         = true
highlight       = true

[widget.results.item.default]
align           = "left"
font            = { size = 14, weight = "normal" }
color           = "$on-surface-variant"
background      = "#00000000"
border          = { radius = 2, width = 0, color = "#FFFFFF0D" }
padding         = [4, 6, 4, 6]
margin          = [0]
comment         = { font = { size = 10, weight = "normal" }, color = "$secondary" }
highlight       = { font = { size = 14, weight = "bold" }, color = "$primary" }

[widget.results.item.selected]
color           = "$on-surface"
background      = "$primary-container"
border          = { radius = 2, width = 1, color = "$primary" }
comment         = { font = { size = 10, weight = "normal" }, color = "$on-secondary-container" }
highlight       = { font = { size = 14, weight = "bold" }, color = "$primary" }

[widget.preview]
enable          = false

[widget.results.count]
enable          = true
format          = "[{count}]"
font            = { size = 10, weight = "normal" }
color           = "$outline"
align           = "left"
padding         = [2, 4, 2, 4]

[widget.clock]
enable          = false
