[meta]
name        = "Spotlight"
description = "MacOS like"

[window]
width           = 700
height          = 480
anchor          = ["center"]
margin          = [0, 0, 0, 0]
background      = "$surface"
border          = { radius = 12, width = 1, color = "$outline-variant" }
exclusive       = false
ignore-exclusive = false
keyboard        = "exclusive"
font            = { family = "sans-serif" }

[widget.input]
font            = { size = 24, weight = "bold" }
color           = "$on-surface"
placeholder     = { text = "Search...", color = "$outline" }
background      = "$surface"
border          = { radius = 0, width = 0, color = "#00000000" }
caret           = { width = 3.0, color = "$primary" }
selection       = { background = "$primary-container", color = "$on-surface" }
padding         = [20, 20, 16, 20]
align           = "left"

[widget.input.prompt]
enable          = false

[widget.results]
direction       = "v"
margin          = [0, 0, 0, 0]
padding         = [8, 12, 12, 12]
gap             = 4
border          = { radius = 0, width = 0, color = "#00000000" }
scroll          = "follow"
reverse         = false

[widget.results.scrollbar]
enable          = true

[widget.results.scrollbar.track]
width           = 4
color           = "#00000000"
padding         = [0]
margin          = [0]
radius          = 4

[widget.results.scrollbar.thumb]
color           = "$outline"
radius          = 4

[widget.results.item]
icon            = { size = 24, gap = 12, enable = true }
comment         = true
highlight       = true
direction       = "v"

[widget.results.item.default]
align           = "left"
font            = { size = 16, weight = "normal" }
color           = "$on-surface-variant"
background      = "#00000000"
border          = { radius = 8, width = 0, color = "#00000000" }
padding         = [12, 16, 12, 16]
margin          = [0]
comment         = { font = { size = 12, weight = "normal" }, color = "$outline" }
highlight       = { font = { size = 16, weight = "bold" }, color = "$primary" }

[widget.results.item.selected]
color           = "$on-surface"
background      = "$surface-container-high"
border          = { radius = 8, width = 0, color = "$primary" }
comment         = { font = { size = 12, weight = "normal" }, color = "$on-surface-variant" }
highlight       = { font = { size = 16, weight = "bold" }, color = "$primary" }

[widget.preview]
enable          = false

[widget.results.count]
enable          = true
format          = "{count} Results"
font            = { size = 12, weight = "normal" }
color           = "$outline-variant"
align           = "right"
padding         = [4, 16, 4, 16]

[widget.clock]
enable          = false
