# Lawnch config
#
# colors: "#RRGGBB", "#RRGGBBAA", "#RGB", "#RGBA",
#         "rgb(r, g, b)", "rgba(r, g, b, a)",
#         "$theme-variable",
#         "lighten(color, %)", "darken(color, %)", "opacity(color, %)",
#         "saturate(color, %)", "desaturate(color, %)",
#         "mix(color1, color2, %)", "invert(color)", "complement(color)",
#         "grayscale(color)", "adjust-hue(color, degrees)"
#
# font colors accept "foreground" as an alias for "color"
#
# padding: single value, [v, h], [top, h, bottom], or [top, right, bottom, left]

[general]
terminal        = "auto"
terminal-flag   = "-e"
editor          = "auto"
locale          = ""

[general.icon]
theme          = "Papirus-Dark"
dirs           = [ "~/.nix-profile/share/icons/hicolor", "/usr/share/pixmaps" ]

[general.history]
enable          = true
max-size        = 100

[appearance.layout]
order           = ["input", "breadcrumbs", "results_count", "results", "clock", "preview"]
direction       = "v" # possible value: v, vertical, h, horizontal. default: vertical
preview-side    = "right" # right or left
[launch]
initial         = ":app"
scope           = ""
command         = "{}"
terminal-command = "{terminal} {terminal-flag} {}"
wrapper         = ""

[keybindings]
inherit           = "default"
"Alt+k"           = "nav-up"
"Alt+j"           = "nav-down"
"Alt+h"           = "nav-left"
"Alt+l"           = "nav-right"
"Shift+BackSpace" = "delete-word"
"Alt+Return"      = "execute"
"Ctrl+Shift+c"    = "clear"


# modifiers are liek fish's abbr and alias
# abbr will extend to expanded value upon space and alias willl be evaluated as expanded without actually rendering it
[[modifier]]
trigger = "gh"
expanded = "github"
type = "abbr"
scope = ["*"]

[[modifier]]
trigger = "h"
expanded = "home"
type = "alias"
scope = [":files-nav", ":fn"]


[window]
width           = 500
height          = 410
anchor          = [ "top" ]
margin          = [140, 0, 0, 0]
padding         = [0]
background      = "opacity(#0b0909, 80%)"
border          = { radius = 8, width = 2, color = "#458588CC" }
exclusive       = false
ignore-exclusive = true
keyboard        = "exclusive"

# font will be inherited by all widgets from window if they are not set and goes like
# widgets font path -> widgets font family -> window font path -> window font family
font            = { path = "/path/to/JetBrainsMonoNerdFont-Regular.ttf", size = 15, weight = "normal" }

[widget.input]
color           = "#EBDBB2"
placeholder     = { text = "Lawnch...", color = "#7C6F64" }
background      = "#00000000"
border          = { radius = 8, width = 1, color = "#00000000" }
caret           = { width = 2, color = "#458588" }
selection       = { background = "#3366CC80", color = "#FFFFFF" }
padding         = [14, 14, 2, 0]
margin          = [0]
align           = "left"
visible         = true

[widget.input.prompt]
enable          = true
text            = " >>"
side            = "left"
color           = "#458588"
background      = "#00000000"
border          = { radius = 0, width = 0, color = "#00000000" }
padding         = [12, 14, 0, 14]
margin          = [0]

[widget.results]
direction       = "v"
column          = 2 # default: 4. only works for horizontal or h direction
margin          = [5, 8, 0, 8]
padding         = [10, 0, 0, 0]
gap             = 2
background      = "opacity(#0b0909, 80%)"
border          = { radius = 12, width = 1, color = "#00000000" }
scroll          = "follow"
reverse         = false
limit           = 50
show-help       = true

[widget.results.scrollbar]
enable          = true

[widget.results.scrollbar.track]
width = 10
color = "#00000000"
padding = [3]
margin = [0]
radius = 5

[widget.results.scrollbar.thumb]
color = "#458588CC"
radius = 5

[widget.results.item]
icon            = { size = 22, gap = 8, enable = true }
comment         = true
highlight       = true
direction       = "v"

[widget.results.item.default]
align           = "left"
color           = "#ffffffff"
background      = "#00000000"
border          = { radius = 3, width = 1, color = "#00000000" }
comment         = { color = "#A5F5A7" }
highlight       = { color = "#FFFF00" }
padding         = [8]
margin          = [0]

# by default selected state will inherit from default unless sepcified and all key under default works for selected
[widget.results.item.selected]
align           = "left"
color           = "#73DEE2"
background      = "#458588A6"
border          = { radius = 3, width = 1, color = "#458588" }
comment         = { color = "#A5F5A7" }
highlight       = { color = "#FFFF00" }
padding         = [8]
margin          = [0]

[widget.results.count]
enable          = true
format          = "{count} results"
color           = "#7C6F64"
align           = "left"
padding         = [2, 8, 2, 20]
margin          = [0]

[widget.preview]
enable          = true
direction       = "v"
preview-image-size      = 120
padding         = [120, 14, 8, 14]
margin          = [0]
background      = "#00000000"
gap             = { v = 6, h = 6 }

[widget.preview.icon]
size = 16
fallback = true

[widget.preview.name]
color           = "#EBDBB2"

[widget.preview.comment]
color           = "#689D6A"

[widget.clock]
enable          = true
format          = "%I:%M"
color           = "#7C6F64E6"
align           = "left"
padding         = [4, 10, 24, 24]
margin          = [0]

[widget.breadcrumbs]
enable          = true
separator       = "/" # will be used to separate sub menu title
color           = "#7C6F64E6"
align           = "left"
padding         = [4, 10, 24, 24]
margin          = [0]

[providers.apps]
command         = ""
uwsm            = false
uwsm-prefix     = "uwsm app --"
history         = true

[providers.bins]
exec            = "spawn" # spawn, terminal, "exec"
history         = true
terminal-exec   = false

# refer to plugins
[plugin.powermenu]
enable          = false
order           = ["lockscreen", "shutdown", "reboot", "suspend", "hibernate"]
lock-cmd        = "hyprlock"
logout-cmd      = "hyprctl dispatch exit"
suspend-cmd     = "systemctl suspend"
reboot-cmd      = "systemctl reboot"
shutdown-cmd    = "systemctl poweroff"

[plugin.wallpapers]
enable          = false
dir             = "~/Pictures/Wallpapers"
limit           = 10
command         = 'awww --img "{}"'

[plugin.files]
enable          = false
limit           = 50
max-depth       = 4
